dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.login, name='login'),
    path('dashboard/', views.index, name='dashboard'),
    path('forget/', views.forget, name='forget'),
    path('change_password/', views.change_password, name='change_password'),
]

matrix_admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls'))
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
import json
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

def index(request):
    return render(request, 'dashboard/index.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        if not username or not password:
            messages.error(request, 'Please enter a valid username and password.')
            return render(request, 'dashboard/login.html')
        # sanitize input
        username = username.strip()
        password = password.strip()
        # check if user exists and password is correct
        with open('Admin.txt', 'r') as f:
            json_string = f.read()
            users = json.loads(json_string)
            if username in users and users[username]['password'] == password:
                role = users[username]['role']
                request.session['role'] = role
                response = render(request, 'dashboard/index.html', {'username': username})
                response.set_cookie("username",username)
                response.set_cookie("user",username)
                return response
            else:
                messages.error(request, 'Invalid credentials...!')
                return render(request, 'dashboard/login.html')
    else:
        return render(request, 'dashboard/login.html')


def forget(request):
    return render(request, 'dashboard/forget.html')

import json
from django.shortcuts import render

def change_password(request):
    if request.method == 'POST':
        with open("Admin.txt", "r") as f:
            users = json.load(f)
        username = request.POST.get('username1')
        new_password = request.POST.get('npass')
        confirm_password = request.POST.get('cpass')
        entered_sc = request.POST.get('security_code')
        print(f"username={username}, new_password={new_password}, confirm_password={confirm_password}, entered_sc={entered_sc}")
        if not username or not new_password or not confirm_password or not entered_sc:
            error_message = "Please fill out all the fields."
            return render(request, "dashboard/forget.html", {'error_message': error_message})
        username = username.strip()
        new_password = new_password.strip()
        confirm_password = confirm_password.strip()
        entered_sc = entered_sc.strip()
        if username not in users:
            error_message = "The username does not exist."
            return render(request, "dashboard/forget.html", {'error_message': error_message})
        elif new_password != confirm_password:
            error_message = "The new password and confirm password do not match."
            return render(request, "dashboard/forget.html", {'error_message': error_message})
        elif users[username]["sc"] != entered_sc:
            error_message = "The security code is incorrect."
            return render(request, "dashboard/forget.html", {'error_message': error_message})
        users[username]["password"] = new_password
        with open("Admin.txt", "w") as f:
            json.dump(users, f)

        success_message = "Password successfully updated."
        return render(request, "dashboard/forget.html", {'success_message': success_message})
    else:
        return render(request, "dashboard/forget.html")

templates/base.html
{% load static %}

{% block html %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
{% block head %}
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/Newproloto.png' %}">
    <title>PROLOTO</title>
            <link href="{% static 'css/bootstrap.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/animation.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/asColorPicker.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/fullcalendar.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/calendar.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/dataTables.bootstrap4.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <!-- <link href="{% static 'css/responsive.bootstrap4.min.css' %?v={{ file.version }}}" rel="stylesheet"/> -->
            <link href="{% static 'css/fontawesome-all.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.gritter.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.minicolors.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.steps.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/magnific-popup.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/materialdesignicons.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/multicheck.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/perfect-scrollbar.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/quill.core.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/quill.snow.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/select2.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/steps.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/themify-icons.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/toastr.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/float-chart.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/style.min.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <link href="{% static 'css/custom.css' %}?v={{ file.version }}" rel="stylesheet"/>
            <!-- <link href="{% static 'css/dashboard.css' %}?v={{ file.version }}" rel="stylesheet"/> -->

{% block extra_style %}
<style>
    
</style>
{% endblock extra_style %}
</head>
{% endblock head %}
   
{% block body %}
<body>
    <!-- Preloader - style you can find in spinners.css' %} -->

    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- Main wrapper - style you can find in pages.scss -->
    <div id="main-wrapper">
        {% include 'dashboard/includes/header.html' %}
        {% include 'dashboard/includes/sidebar.html' %}
        <div class="page-wrapper">
        {% block content %}{% endblock content %}
        {% include 'dashboard/includes/footer.html' %}
        </div>
    </div>
    {% block script %}    
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}"></script>
        <script src="{% static 'js/sparkline.js' %}"></script>
        <script src="{% static 'js/waves.js' %}"></script>
        <script src="{% static 'js/sidebarmenu.js' %}"></script>
        <script src="{% static 'js/custom.min.js' %}"></script>

        <script src="{% static 'js/excanvas.js' %}"></script>
        <script src="{% static 'js/jquery.flot.js' %}"></script>
        <script src="{% static 'js/jquery.flot.pie.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.stack.js' %}"></script>
        <script src="{% static 'js/jquery.flot.crosshair.js' %}"></script>
        <script src="{% static 'js/jquery.flot.tooltip.min.js' %}"></script>
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/chart-page-init.js' %}"></script>
        <script src="{% static 'js/app-style-switcher.js' %}"></script>
        <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'js/datatable-checkbox-init.js' %}"></script>
        <script src="{% static 'js/datatables.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
        <!-- <script src="{% static 'js/dataTables.responsive.min.js' %}"></script> -->
        <!-- <script src="{% static 'js/responsive.bootstrap4.min.js' %}"></script> -->
        <script src="{% static 'js/jquery.charts-sparkline.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/jquery-asColor.min.js' %}"></script>
        <script src="{% static 'js/jquery-asGradient.js' %}"></script>
        <script src="{% static 'js/jquery-asColorPicker.min.js' %}"></script>
        <script src="{% static 'js/jquery.minicolors.min.js' %}"></script>
        <script src="{% static 'js/jquery.multicheck.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/toastr.min.js' %}"></script>
        <!-- <script src="{% static 'js/select2.full.min.js' %}"></script> -->
        <script src="{% static 'js/select2.min.js' %}"></script>
        <script src="{% static 'js/jquery.inputmask.bundle.min.js' %}"></script>
        <script src="{% static 'js/quill.min.js' %}"></script>
        <script src="{% static 'js/mask.init.js' %}"></script>
        <script src="{% static 'js/meg.init.js' %}"></script>
        <!-- <script src="{% static 'js/cal-init.js' %}"></script> -->
        <!-- <script src="{% static 'constant/strings.js' %}"></script>
        <script src="{% static 'constant/validator.js' %}"></script> -->

        <script>
            $(document).ready(function () {
                $('#example').DataTable();
            });
        </script>
        <script>
            $(document).ready(function () {
                $('#zero_config').DataTable();
            });
        </script>

    {% block extra_script %}{% endblock extra_script %}

    
    {% endblock script %}

    </body>
{% endblock body %}


{% endblock html %}

templates/dashboard/forget.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
  <title>Login | Smart Lockout Tagout System</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="{% static 'js\bootstrap.bundle.min.js' %}"></script>
  <style>
    .form-control::placeholder {
      font-size: 14px; /* adjust the size to your preference */
    }
  </style>
  {% bootstrap_css %}
</head>
<body style="background-color: rgb(38,40,61);">
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-3 d-none d-md-block bg-dark sidebar" style="background-color:rgb(87, 93, 168); height: 100vh;">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
          <img class="logo img-fluid" src="{% static 'images/proloto.png' %}" alt="logo.png">
          <h6 class="description" style="color: aliceblue;">Smart Lockout Tagout System</h6>
        </div>
      </nav>
      <main role="main" class="col-md-9 ml-sm-auto col-lg-8 px-4">
        <div class="row justify-content-center text-center" style="padding-top: 20px;">
          <div class="col-md-6">
            <form method='POST' class="text-left" action="/change_password/">
              {% csrf_token %}
              <h6 class="title mb-3" style="color: aliceblue;">Change Your Password</h6>
              <div class="form-group">
                <label for="username" style="color: aliceblue;">Username</label>
                <input type="text" name="username1" placeholder="Type your Username" class="form-control"  required>
              </div>
              <div class="form-group">
                <label for="password" style="color: aliceblue;">New Password</label>
                <input type="password" name="npass" placeholder="Type your Username" class="form-control"  required>
              </div>
              <div class="form-group">
                <label for="password" style="color: aliceblue;">Confirm Password</label>
                <input type="password" name="cpass" placeholder="Type your Username" class="form-control" required>
              </div>
              <div class="form-group">
                <label for="security_code" style="color: aliceblue;">Security Code</label>
                <div class="input-group">
                  <input type="texy" name="security_code" placeholder="Type your password" id="password" class="form-control" required>
                  <div class="input-group-append">
                    <span class="input-group-text">
                      <i class="fa fa-eye" aria-hidden="true" id="togglePassword"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <a href="{% url 'dashboard:login' %}">Back to Login Page</a> 
              </div>
              <div class="form-group">  
                <button class="btn btn-primary btn-block" type="submit">Change Password</button>
                <div style="text-align: center; color: aliceblue;">
                  {% if success_message %}
                  <h7{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ success_message }}</h7>
                  {% endif %}
                  {% if error_message %}
                  <h7{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ error_message }}</h7>
                  {% endif %}
                </div>
              </div>
            </form>
          </div>
        </div>
      </main>
    </div>
  </div>
</body>
</html>

templates/dashboard/includes/footer.html
{% load static %}
<footer class="footer fixed-bottom bg-dark text-center py-3">
  <div class="container">
    <div class="row justify-content-between align-items-center">
      <span class="d-block col-auto">INDEC-4.0 &copy; SMART Devices</span>
      <div class="col-auto">
        <!-- <img src="{% static 'images/indec.ico' %}" alt="indec.png" class="img-fluid" style="max-width: 30%; height: 10%;"> -->
      </div>
    </div>
  </div>
</footer>

templates/dashboard/includes/header.html
{% load static %}
<header class="topbar" data-navbarbg="skin5">
            <nav class="navbar fixed-top top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <!-- This is for the sidebar toggle which is visible on mobile only -->
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    <a class="navbar-brand" href=""> <!--index.html-->
                       <!-- <span>
                             <img src="{% static 'images/proloto.ico' %}" alt="homepage" class="logo-icon" style="padding-left: 1vh;width: 98px; height: 98px;" />                           
                            </span> -->
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <!-- toggle and nav items -->
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="d-none d-md-block">Dashboard <i class="fa fa-angle-down"></i></span>
                            <span class="d-block d-md-none"><i class="fa fa-plus"></i></span>   
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Assets</a>
                                <a class="dropdown-item" href="#">User</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Report</a>
                            </div>
                        </li>
                        <li class="nav-item search-box"> <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <form class="app-search position-absolute">
                                <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                            </form>
                        </li>
                    </ul>
                    <ul class="navbar-nav float-right">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="mdi mdi-bell font-24"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">FAQ</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="font-24 mdi mdi-comment-processing"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown" aria-labelledby="2">
                                <ul class="list-style-none">
                                    <li>
                                        <div class="">
                                            <a href="javascript:void(0)" class="link border-top">
                                                <div class="d-flex no-block align-items-center p-10">
                                                    <span class="btn btn-info btn-circle"><i class="ti-settings"></i></span>
                                                    <div class="m-l-10">
                                                        <h5 class="m-b-0">Settings</h5> 
                                                        <span class="mail-desc">Customize the template</span> 
                                                    </div>
                                                </div>
                                            </a>
                                            <a href="javascript:void(0)" class="link border-top">
                                                <div class="d-flex no-block align-items-center p-10">
                                                    <span class="btn btn-primary btn-circle"><i class="ti-user"></i></span>
                                                    <div class="m-l-10">
                                                        <h5 class="m-b-0">Manasi</h5> 
                                                        <span class="mail-desc">Admin...!</span> 
                                                    </div>
                                                </div>
                                            </a>
                                            <!-- Message -->
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{% static 'images/users/1.jpg' %}" alt="user" class="rounded-circle" width="31"></a>
                            <div class="dropdown-menu dropdown-menu-right user-dd animated">
                                <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user m-r-5 m-l-5"></i> Profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="javascript:void(0)"><i class="ti-settings m-r-5 m-l-5"></i> Account Setting</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="javascript:void(0)"><i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                                <div class="dropdown-divider"></div>
                                <div class="p-l-30 p-10"><a href="javascript:void(0)" class="btn btn-sm btn-success btn-rounded">View Profile</a></div>
                            </div>
                        </li>
                        <!-- Profile and search -->
                    </ul>
                </div>
            </nav>
        </header>

templates/dashboard/includes/sidebar.html
{% load static %}
  <aside class="left-sidebar scrollable ps-container ps-theme-default ps-active-y" data-sidebarbg="skin5">
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="mdi mdi-laptop-chromebook"></i><span class="hide-menu">Assets</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="mdi mdi-account-outline"></i><span class="hide-menu">User</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="mdi mdi-library-books"></i><span class="hide-menu">Reports</span></a></li>
                    </ul>
                </nav>
            </div>
        </aside>

templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="d-flex justify-content-center">
  <div class="p-3 bg-danger text-white flex-fill">
    Flexbox 1
  </div>
  <div class="p-3 bg-primary text-white flex-fill d-flex flex-column">
    <div class="d-flex">
      <div class="p-3 bg-secondary text-white flex-fill">
        Column 1
      </div>
      <div class="p-3 bg-info text-white flex-fill">
        Column 2
      </div>
    </div>
    <div class="p-3 bg-secondary text-white flex-fill mt-3">
      Row 2
    </div>
  </div>
  <div class="p-3 bg-success text-white flex-fill">
    Flexbox 3
  </div>
  <div class="p-3 bg-danger text-white flex-fill d-flex flex-column">
    <div class="d-flex">
      <div class="p-3 bg-secondary text-white flex-fill">
        Column 1
      </div>
      <div class="p-3 bg-info text-white flex-fill">
        Column 2
      </div>
    </div>
    <div class="p-3 bg-secondary text-white flex-fill mt-3">
      Row 2
    </div>
  </div> 
  <div class="p-3 bg-purple text-white flex-fill">
    Flexbox 5
  </div>
</div>
{% endblock %}

templates/dashboard/login.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
  <title>Login | Smart Lockout Tagout System</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="{% static 'js\bootstrap.bundle.min.js' %}"></script>
  <style>
    .form-control::placeholder {
      font-size: 14px; /* adjust the size to your preference */
    }
  </style>
  {% bootstrap_css %}
</head>
<body style="background-color: rgb(38,40,61);">
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-3 d-none d-md-block bg-dark sidebar" style="background-color:rgb(84, 86, 120); height: 100vh;">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
          <img class="logo img-fluid" src="{% static 'images/proloto.png' %}" alt="logo.png">
          <h6 class="description" style="color: aliceblue;">Smart Lockout Tagout System</h6>
        </div>
      </nav>
      <main role="main" class="col-md-9 ml-sm-auto col-lg-8 px-4">
        <div class="row justify-content-center text-center" style="padding-top: 140px;">
          <div class="col-md-6">
            <form method='POST' class="text-left">
              {% csrf_token %}
              <h6 class="title mb-3" style="color: aliceblue;">Login To Your Account</h6>
              <div class="form-group">
                <label for="username" style="color: aliceblue;">Username</label>
                <input type="text" name="username" placeholder="Type your Username" class="form-control form-control-lg" style="font-size: 1rem;" required>
              </div>
              <div class="form-group">
                <label for="password" style="color: aliceblue;">Password</label>
                <div class="input-group">
                  <input type="password" name="password" placeholder="Type your password" id="password" class="form-control" required>
                  <div class="input-group-append">
                    <span class="input-group-text">
                      <i class="fa fa-eye" aria-hidden="true" id="togglePassword"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <a href="{% url 'dashboard:forget' %}">Forget Password?</a> 
              </div>
              <div class="form-group">
                <button class="btn btn-primary btn-block">Login</button>
                <div style="text-align: center; color: aliceblue;">
                    {% for m in messages %}
                    <h7>{{m}}</h7>
                    {% endfor %}
              </div>
              </div>
            </form>
          </div>
        </div>
      </main>
    </div>
  </div>
  {% bootstrap_javascript %}
  <script>
    const togglePassword = document.querySelector('#togglePassword');
    const password = document.querySelector('#password');
    togglePassword.addEventListener('click', function (e) {
      const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
      password.setAttribute('type', type);
      this.classList.toggle('fa-eye-slash');
      this.classList.toggle('fa-eye');
    });
  </script>
</body>
</html>